# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo_Project' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Demo_Project

  target 'Demo_Project-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'Demo_ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Demo_Project-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Demo_Project-tvOS

  target 'Demo_Project-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
